kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jialei
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # 申请的资源大小
