kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-cephfs-pvc
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # 申请的资源大小
