apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: my-first-ubuntu-tf
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my-ubuntu-tf
  template:
    metadata:
      labels:
        name: my-ubuntu-tf
    spec:
      hostNetwork: true
      hostIPC: true
      containers:
      - name: orion-client-hvd
        imagePullPolicy: Always
        image: harbor.iiis.co/library/ubuntu-tensorflow:2.3.0  # 可自行更改镜像和版本
        command: ["bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        resources: # 描述申请的机器资源
          limits:
            cpu: 4 # 最大CPU
            memory: 10Gi # 最大内存
            virtaitech.com/gpu: 1  # 最大GPU数目
          requests:
            cpu: 4 # 最小需要的CPU数目 （如果目前资源不够，就放弃启动）
            memory: 8Gi # 最小需要申请的内存的数目（如果目前资源不够，就放弃启动）
            virtaitech.com/gpu: 1  # 最小需要的GPU数目
        env:
          - name : ORION_GMEM
            value : "10000"  # 每张显卡的显存，单位为M
          - name : ORION_RATIO
            value : "100"
          - name: ORION_VGPU
            value: "1"
          - name: ORION_RESERVED
            value: "0"
          - name: ORION_CROSS_NODE
            value: "1"
          - name : ORION_GROUP_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
